name: Publish

on:
  workflow_dispatch:

jobs:

  publish:
    runs-on: windows-2022

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}
          fetch-depth: 0

      - name: Fetch distro branch
        uses: actions/checkout@v4
        with:
          ref: distro
          fetch-depth: 0
          path: distro

      - name: Make setup installer & portable app
        run: |
          mkdir distro\publish
          Compress-Archive -Path bin\* -DestinationPath distro\publish\portable.zip -Force
          cd distro
          & "$env:ProgramFiles (x86)\Inno Setup 6\iscc.exe" setup.iss

      - name: Upload installer output
        uses: actions/upload-artifact@v4
        id: artifact-upload-installer-step
        with:
          name: setup-installer
          path: |
            distro/out/*.exe

      - name: Delete unwanted artifacts
        uses: geekyeggo/delete-artifact@v5
        with:
          name: "*"

      - name: Upload signed output
        uses: actions/upload-artifact@v4
        with:
          name: ${{ needs.build.outputs.artifact-name }}
          path: distro/publish/
